spring:
  application:
    name: springcloud-config-server
  profiles:
    active: native

server:
  port: 9005
eureka:
  client:
    server-url:
      defaultZone: http://server:7000/eureka/, http://server2:7000/eureka/